require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VictimsController do

  # This should return the minimal set of attributes required to create a valid
  # Victim. As you add validations to Victim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VictimsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all victims as @victims" do
      victim = Victim.create! valid_attributes
      get :index, {}, valid_session
      assigns(:victims).should eq([victim])
    end
  end

  describe "GET show" do
    it "assigns the requested victim as @victim" do
      victim = Victim.create! valid_attributes
      get :show, {:id => victim.to_param}, valid_session
      assigns(:victim).should eq(victim)
    end
  end

  describe "GET new" do
    it "assigns a new victim as @victim" do
      get :new, {}, valid_session
      assigns(:victim).should be_a_new(Victim)
    end
  end

  describe "GET edit" do
    it "assigns the requested victim as @victim" do
      victim = Victim.create! valid_attributes
      get :edit, {:id => victim.to_param}, valid_session
      assigns(:victim).should eq(victim)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Victim" do
        expect {
          post :create, {:victim => valid_attributes}, valid_session
        }.to change(Victim, :count).by(1)
      end

      it "assigns a newly created victim as @victim" do
        post :create, {:victim => valid_attributes}, valid_session
        assigns(:victim).should be_a(Victim)
        assigns(:victim).should be_persisted
      end

      it "redirects to the created victim" do
        post :create, {:victim => valid_attributes}, valid_session
        response.should redirect_to(Victim.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved victim as @victim" do
        # Trigger the behavior that occurs when invalid params are submitted
        Victim.any_instance.stub(:save).and_return(false)
        post :create, {:victim => { "name" => "invalid value" }}, valid_session
        assigns(:victim).should be_a_new(Victim)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Victim.any_instance.stub(:save).and_return(false)
        post :create, {:victim => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested victim" do
        victim = Victim.create! valid_attributes
        # Assuming there are no other victims in the database, this
        # specifies that the Victim created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Victim.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => victim.to_param, :victim => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested victim as @victim" do
        victim = Victim.create! valid_attributes
        put :update, {:id => victim.to_param, :victim => valid_attributes}, valid_session
        assigns(:victim).should eq(victim)
      end

      it "redirects to the victim" do
        victim = Victim.create! valid_attributes
        put :update, {:id => victim.to_param, :victim => valid_attributes}, valid_session
        response.should redirect_to(victim)
      end
    end

    describe "with invalid params" do
      it "assigns the victim as @victim" do
        victim = Victim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Victim.any_instance.stub(:save).and_return(false)
        put :update, {:id => victim.to_param, :victim => { "name" => "invalid value" }}, valid_session
        assigns(:victim).should eq(victim)
      end

      it "re-renders the 'edit' template" do
        victim = Victim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Victim.any_instance.stub(:save).and_return(false)
        put :update, {:id => victim.to_param, :victim => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested victim" do
      victim = Victim.create! valid_attributes
      expect {
        delete :destroy, {:id => victim.to_param}, valid_session
      }.to change(Victim, :count).by(-1)
    end

    it "redirects to the victims list" do
      victim = Victim.create! valid_attributes
      delete :destroy, {:id => victim.to_param}, valid_session
      response.should redirect_to(victims_url)
    end
  end

end
